LIST(APPEND CMAKE_PROGRAM_PATH "$ENV{VSAPPIDDIR}/../../VC/Tools/Llvm/x64/bin/")

set(CMAKE_C_COMPILER clang-cl)
set(CMAKE_CXX_COMPILER clang-cl)
set(CMAKE_CXX_LINKER lld-link)

set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Wno-error=unused-command-line-argument /Zc:__cplusplus /MP /O2 /Ob3 /Oi /Oy /Ot /GL -flto -fmerge-all-constants -fwhole-program-vtables /W4 /GF /arch:AVX2 /Zi /GT /MD /DNDEBUG")

set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /RELEASE /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "${CMAKE_MODULE_LINKER_FLAGS_RELEASE} /DEBUG /RELEASE /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG /RELEASE /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")

set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Wno-error=unused-command-line-argument /Zc:__cplusplus /MP /O2 /Ob3 /Oi /Oy /Ot /GL -flto -fmerge-all-constants -fwhole-program-vtables /W4 /GF /arch:AVX2 /Zi /GT /MDd")

set(CMAKE_EXE_LINKER_FLAGS_DEBUG "${CMAKE_EXE_LINKER_FLAGS_DEBUG} /DEBUG /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")
set(CMAKE_MODULE_LINKER_FLAGS_DEBUG "${CMAKE_MODULE_LINKER_FLAGS_DEBUG} /DEBUG /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")
set(CMAKE_SHARED_LINKER_FLAGS_DEBUG "${CMAKE_SHARED_LINKER_FLAGS_DEBUG} /DEBUG /OPT:REF /OPT:ICF /INCREMENTAL:NO /LTCG")
