my %targets = (
    "VC-WIN64A-CLANGASM" => {
        inherit_from     => [ "VC-WIN64-common" ],
        sys_id           => "WIN64A",
        uplink_arch      => 'x86_64',
        asm_arch         => 'x86_64',
        AS               => "\$(CC)",
        ASFLAGS          => "\$(CFLAGS)",
        asflags          => "/c",
        asoutflag        => "/Fo",
        perlasm_scheme   => "mingw64",
        multilib         => "-x64",
    },
);
